model:
  filters: 64
  kernel: 5
  padding: "same"
  activation: "relu"
  num_conv_blocks: 3
training:
  learning_rate: 0.0001
  batch_size: 32
  num_epochs: 20
  early_stopping_patience: 10
data:
  use_knocks: True
  use_slaps: True
  binarize: True
  feature: "melspectrogram" # or mfcc
  train_ratio: 0.8
  val2test_ratio: 0.5
features:
  sampling_rate: 44100
  frame_length: 1024
  frame_step: 256
  fft_length: 1024
  lower_edge_hz: 0.0
  upper_edge_hz: 22050.0
  num_mel_bins: 80
  eps: 0.000001
  num_mfccs: 13






