model:
  filters: [32, 64]
  kernel: 3
  activation: "relu"
  dense_dim: 128
training:
  learning_rate: 0.0001
  batch_size: 8
  num_epochs: 300
  early_stopping_patience: 15
data:
  max_length: 22050
  use_knocks: True
  use_slaps: True
  feature: "melspectrogram"
  train_ratio: 0.8
  val2test_ratio: 0.5
features:
  sampling_rate: 44100
  frame_length: 2048
  frame_step: 512
  fft_length: 2048
  lower_edge_hz: 80.0
  upper_edge_hz: 22050.0
  num_mel_bins: 80
  eps: 0.000001
  num_mfccs: 13






